### ISSUE TITLE
Update name to avoid confusion?

### ISSUE THREAD

**Issue by leonhma** [LinusReuter/lemon-markets-api-access#5]
Imo it'd be pretty helpful to decide on a name. Either 'lemon_markets' or 'lemon_markets_sdk'. I'd go with the first one, because it's shorter and the package on pypi is free.

If youre ok with that, i can make changes to the code on my branch because im already working on new features and the beta

**Comment by LinusReuter** [comment]
as the lemon.markets API has changed to an only commercial usage and I lost interest will I simply archive this repo
